### ISSUE TITLE
base template name

### ISSUE THREAD

**Issue by cwurld** [bitmazk/django-calendarium#49]
Hi,

Have you considered changing the name of 'base.html' to something like 'calendarium_base.html'? I suspect lots of projects already have a 'base.html'. Users could either just use yours or could over-ride it in their code.

Thanks

**Comment by Tyrdall** [comment]
@cwurld Well, it's only used for test purposes in this app (we should have added it to the ``test_app``directory though :)), since we assume, that every Django project got its own ``base.html``. App templates should always extend the ``base.html``.

To override our ``base.html``simply put your own ``base.html``into your template folder.

**Comment by cwurld** [comment]
Yes, that is the problem. Most of my project has nothing to do with a calendar. So I do not want to write my base.html so it works with Calendarium and the rest of my project. I would rather have a template in my template folder that works with Calendarium along with my base template that works with the rest of my project.

**Comment by Tyrdall** [comment]
@cwurld That's a quite unusual setup :) Then I suggest you copy the calendarium template folder into your project template folder and override the calendarium templates.

**Comment by mbrochh** [comment]
@cwurld the only assumption that our calendarium templates make is that your base template is called "base.html" and that it has a `{% block main %}{% endblock %}`.

Is that not the case in your setup? i.e., did you name your base template differently and does it not have a "main" block? In that case, you can simply create a "base.html" that extends your own base template (whatever it's name) and looks something like this:

```
# new file base.html
{% extends "your_own_base_template.html" %}
{% block your_own_main_content_block %}
    {% block main %}{% endblock %}
{% endblock %}
```

That should do the trick, so you just need to add one more file. If you already have a base template and it is indeed called "base.html", I assume it is just lacking the "main" block - couldn't you just add that block right after your own main content block? That block would be ignored by all your own templates and only be used by the calendarium templates. I guess adding that single line of code to your base template wouldn't be too bad?

**Comment by cwurld** [comment]
Before I posted this request, I did what you said and added a "main" block. I agree that's not too bad. A small addition to my code, that makes calendarium work and is ignore by the rest of my code.

Then I realized I needed a CSS file for calendarium. Sure I could add that to my base.html and load it for all pages. The browser would probably cache it. So no real performance drag. But what's next?

It seemed to me that the root of the problem is the name of the calendarium template base file. If you changed it's name, it would not harm your code and it would give users as much control as they wanted. Moreover, you app would work "right out of the box".

**Comment by mbrochh** [comment]
We usually don't ship reusable apps with fully fledged markup and CSS. The templates that come with our apps are just to show the basic usecase and what variables are available in the template context.

This is so that you can plugin the app and see it working - but it will look ugly.

There is no point to create perfect markup and CSS because 90% of all people who will hook up this app will want to manipulate the markup and CSS anyways.

So you were right: If you want to change the look and feel of the app, you need to override all our templates and you need to add your own CSS. We usually only ship one monolithic CSS file for the whole website, so I never thought that it might be a problem that you have to add the additional calendarium CSS to the whole page.
